### ISSUE TITLE
fails with Node.js v18.3.0

### ISSUE THREAD

**Issue by derhuerst** [mildsunrise/node_netlink#17]
```shell
node -v
# v18.3.0
uname -a
# Linux bbnavi-gtfs-rt-feed 5.4.0-117-generic #132-Ubuntu SMP Thu Jun 2 00:39:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
npm ls --depth 1 | grep netlink
# │ ├── netlink@0.2.2
```

```js
const {createRtNetlink, rt} = require('netlink')
createRtNetlink({ref: false})
```

```
TypeError: Cannot define property domain, object is not extensible
    at defineProperty (<anonymous>)
    at AsyncHook.init (node:domain:80:9)
    at NativeNetlink.emitInitNative (node:internal/async_hooks:202:43)
    at new RawNetlinkSocket (/var/www/bbnavi-gtfs-rt-feed.jannisr.de/node_modules/netlink/dist/raw.js:85:25)
    at createNetlink (/var/www/bbnavi-gtfs-rt-feed.jannisr.de/node_modules/netlink/dist/netlink.js:314:20)
    at createRtNetlink (/var/www/bbnavi-gtfs-rt-feed.jannisr.de/node_modules/netlink/dist/rt/rt.js:450:48)
    at REPL2:1:1
    at Script.runInThisContext (node:vm:129:12)
    at REPLServer.defaultEval (node:repl:571:29)
    at bound (node:domain:421:15)
```

**Comment by derhuerst** [comment]
Is there anything I can help with to debug this problem?

**Comment by mildsunrise** [comment]
oh, I see. I think I know what it is

**Comment by mildsunrise** [comment]
should be fixed in latest `main` :) can't release now, I'll probably do it tomorrow

**Comment by derhuerst** [comment]
Thanks!

**Comment by mildsunrise** [comment]
apologies, I forgot about this :sweat_smile: 0.2.3 is up
